# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLDbVbEjQHpBBuZr19JuukRx3yFaOg3q
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
import torchvision.transforms as transforms

from dataset import RsDataset
from utils import train_epoch, val_epoch
from model import USSFCNet, CMConv  # your model file

# also import these if defined elsewhere
from metrics import ConfusionMatrix, get_score_sum

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

if __name__ == '__main__':
    # 1. Initialize Network
    net = USSFCNet(3, 1, ratio=0.5).to(device)

    # Parameter count
    total_allocated = sum(p.numel() for p in net.parameters() if p.requires_grad)
    masked_zeros = sum(m.mask.sum().item() for m in net.modules() if isinstance(m, CMConv))
    active_params = total_allocated - masked_zeros

    print(f"\n{'='*45}")
    print(f"PyTorch Allocated Memory: {total_allocated:,} params")
    print(f"Theoretical Active Memory: {active_params:,} params")
    print(f"{'='*45}\n")

    # 2. Data
    trans = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize([0.5], [0.5])
    ])

    ds_train = RsDataset(train_src_t1, train_src_t2, train_label, trans)
    ds_val = RsDataset(test_src_t1, test_src_t2, test_label, trans)

    dl_train = DataLoader(ds_train, batch_size=8, shuffle=True, num_workers=2)
    dl_val = DataLoader(ds_val, batch_size=1, shuffle=False)

    # 3. Loss & Optimizer
    crit = nn.BCELoss()
    opt = optim.Adam(net.parameters(), lr=1e-4, betas=(0.9, 0.999), weight_decay=0.0005)

    # 4. Training Loop
    best_f1 = 0
    os.makedirs('ckps', exist_ok=True)

    for epoch in range(200):
        print(f'--- Epoch {epoch+1}/200 ---')

        loss, train_res = train_epoch(net, dl_train, crit, opt, device, ConfusionMatrix, get_score_sum)
        val_res = val_epoch(net, dl_val, device, ConfusionMatrix, get_score_sum)

        cur_f1 = val_res['f1'][1]
        print(f'Train Loss: {loss:.4f} | Val F1: {cur_f1:.4f}')

        if cur_f1 > best_f1:
            best_f1 = cur_f1
            torch.save(net.state_dict(), 'ckps/best_model.pth')
            print(f'*** Saved Best Model (F1: {best_f1:.4f}) ***')

        print("-" * 30)