# -*- coding: utf-8 -*-
"""visualize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLDbVbEjQHpBBuZr19JuukRx3yFaOg3q
"""

import torch
import matplotlib.pyplot as plt
import numpy as np
from glob import glob

from model import USSFCNet

def run_visualization(ds_val, device, num_samples=4):
    model_search = glob('/kaggle/input/**/best_model*.pth', recursive=True)

    if not model_search:
        print("Model not found!")
        return

    model_path = model_search[0]
    print(f"Loading: {model_path}")

    net = USSFCNet(3, 1, ratio=0.5).to(device)
    net.load_state_dict(torch.load(model_path, map_location=device))
    net.eval()

    indices = np.random.choice(len(ds_val), num_samples, replace=False)

    fig, axes = plt.subplots(num_samples, 4, figsize=(20, num_samples * 5))

    if num_samples == 1:
        axes = np.expand_dims(axes, axis=0)

    for i, idx in enumerate(indices):
        t1, t2, label = ds_val[idx]

        inp1 = t1.unsqueeze(0).to(device)
        inp2 = t2.unsqueeze(0).to(device)

        with torch.no_grad():
            output = net(inp1, inp2)
            pred = (output > 0.5).float().cpu().squeeze().numpy()

        img1 = t1.permute(1, 2, 0).numpy() * 0.5 + 0.5
        img2 = t2.permute(1, 2, 0).numpy() * 0.5 + 0.5
        gt = label.squeeze().numpy()

        axes[i, 0].imshow(np.clip(img1, 0, 1))
        axes[i, 0].set_title("Time 1")

        axes[i, 1].imshow(np.clip(img2, 0, 1))
        axes[i, 1].set_title("Time 2")

        axes[i, 2].imshow(gt, cmap='gray')
        axes[i, 2].set_title("Ground Truth")

        axes[i, 3].imshow(pred, cmap='magma')
        axes[i, 3].set_title("Prediction")

        for ax in axes[i]:
            ax.axis('off')

    plt.tight_layout()
    plt.show()